name: TypeScript Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Instaling node_modules...
      run: npm install
    - name: Excuting Test...
      run: npm run build
    - name: Building...
      run: npm run build
    - name: Packing...
      uses: actions/upload-artifact@v1
      with: 
        name: dist
        path: /**
