name: TypeScript Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install node module
      run: npm install
    - name: Building Application
      run: npm run test
