name: Development Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installing node_modules...
      run: npm install
    - name: Executing Test...
      run: npm run test
    - name: Building...
      run: npm run build
    - name: Packing...
      run: node ./build/createpack.js "*"
    - name: Artifacts...
      uses: actions/upload-artifact@v1
      with: 
        name: package
        path: ./package