name: Development Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installing node_modules...
      run: npm install
    - name: Executing Test...
      run: npm run test
    - name: Building...
      run: npm run build
    - name: Packing...
      run: npm run create-pack "v0.0.4-beta"
    - name: Artifacts...
      uses: actions/upload-artifact@v1
      with: 
        name: package
        path: ./package
       - name: Publishing...
      run: |
        node ./build/publish.js $NODE_AUTH_TOKEN "v0.0.4-beta"
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_PUBLISH }}

