name: TypeScript Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Instaling node_modules...
      run: npm install
    - name: Excuting Test...
      run: npm run test
    - name: Building...
      run: npm run build
    - name: Packing...
      run: npm run create-pack
    - name: Artifacting...
      uses: actions/upload-artifact@v1
      with: 
        name: package
        path: ./package
    - name: Publishing...
      run: |
        npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
        npm publish "package/data-lib-1.0.0.tgz"
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
