name: Release Build

on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Instaling node_modules...
      run: npm install
    - name: Building...
      run: npm run build
    - name: Packing...
      run: npm run create-pack
    - name: Publishing...
      run: |
        node ./build/publish.js $NODE_AUTH_TOKEN
        npm publish azdreamic-data-lib-0.0.3-beta.tgz
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_PUBLISH }}
