name: Release Build

on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installing node_modules...
      run: npm install
    - name: Building...
      run: npm run build
    - name: Building Package Modules...
      run: npm run webpack:build
    - name: Packing...
      run: node ./build/createpack.js ${GITHUB_REF/refs\/tags\//}
    - name: Publishing...
      run: |
        node ./build/publish.js $NODE_AUTH_TOKEN ${GITHUB_REF/refs\/tags\//}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_PUBLISH }}
